#!/bin/sh
if [ "$REDIS_ENV" = "PROD" -o "$REDIS_ENV" = "STAGE" ];
then
  cp /usr/local/bin/redis-prod.conf /etc/redis/redis.conf 
else
  cp /usr/local/bin/redis-nonprod.conf /etc/redis/redis.conf 
fi

/usr/local/bin/redis-server /etc/redis/redis.conf
